language: r
warnings_are_errors: false
sudo: required

notifications:
  email:
    recipients:
      - nicolas.casajus@fondationbiodiversite.fr

r_packages:
  - R2OpenBUGS
  - rjags
  - R2jags
  - writexl

before_install:
  - sudo apt-get install --yes jags

before_script:
  - wget http://www.openbugs.net/w/OpenBUGS_3_2_3?action=AttachFile&do=get&target=OpenBUGS-3.2.3.tar.gz
  - mv "OpenBUGS_3_2_3?action=AttachFile&do=get&target=OpenBUGS-3.2.3.tar.gz" OpenBUGS-3.2.3.tar.gz
  - tar -zxvf /tmp/OpenBUGS-3.2.3.tar.gz
  - cd /tmp/OpenBUGS-3.2.3
  - ./configure
  - make
  - sudo make install
